### ISSUE TITLE
 throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by huguiqi** [mytharcher/rainbow#4]
hello,please help me, tell me why? thank you very much
I got this error:

/usr/local/bin/node app.js
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at Object.exports.route (/Users/samhu/Public/nodeWorkSpace/testExpress/node_modules/rainbow/index.js:56:21)
    at Object.<anonymous> (/Users/samhu/Public/nodeWorkSpace/testExpress/app.js:29:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

Process finished with exit code 1

**Comment by mytharcher** [comment]
Could you show your code in `app.js` or any other useful information related with your test project? In rainbow's code the only related code is in index.js at line 56:

    path.join(approot, (paths.controllers || 'controllers'));

Were you using any config option for rainbow?
